### ISSUE TITLE
Checkbox is pixelated

### ISSUE THREAD

**Issue by anonimuos** [stefankueng/tools#48] opened 2021-02-02 12:28 UTC
On high DPI display, checkbox for SKTimestamp is pixelated. Can you fix it? :)

![image](https://user-images.githubusercontent.com/46422834/106600301-3a1b0280-6580-11eb-9aba-e2a3af378d64.png)

**Comment by stefankueng** [comment] 2021-02-02 16:58
unfortunately, no.
The problem is that while explorer is marked as high-dpi aware, it removes those flags for the shell extensions.
Sorry.

**Closed by stefankueng** 2021-02-02 16:58 UTC

**Comment by anonimuos** [comment] 2021-02-02 20:04
But maybe you can use a different control that scales correctly? Or place the checkbox outside to the left of the date box? It looks so ugly! How do the checkboxes on General tab (Attributes), or Compatibility tab not have this problem?

**Comment by stefankueng** [comment] 2021-02-02 20:31
the checkboxes on the general tab are not provided by shell extensions but the explorer itself. So they don't suffer from this restriction.
